export enum AbilityKey {
    STRENGTH = 'STRENGTH',
    DEXTERITY = 'DEXTERITY',
    CONSTITUTION = 'CONSTITUTION',
    INTELLIGENCE = 'INTELLIGENCE',
    WISDOM = 'WISDOM',
    CHARISMA = 'CHARISMA'
}
