export enum ClassType {
    ENVOY = 'ENVOY',
    MECHANIC = 'MECHANIC',
    MYSTIC = 'MYSTIC',
    OPERATIVE = 'OPERATIVE',
    SOLARIAN = 'SOLARIAN',
    SOLDIER = 'SOLDIER',
    TECHNOMANCER = 'TECHNOMANCER'
}
